#include "errmsg.h"

#include <algorithm>
#include <iterator>

namespace {

struct ErrorMessage {
	DWORD code;
	const char *text;
};

// Generated from Wine's dlls/kernelbase/winerror.mc (ENU); messages containing % inserts are omitted.
constexpr ErrorMessage kErrorMessages[] = {
	{0, "Success.\r\n"},
	{1, "Invalid function.\r\n"},
	{2, "File not found.\r\n"},
	{3, "Path not found.\r\n"},
	{4, "Too many open files.\r\n"},
	{5, "Access denied.\r\n"},
	{6, "Invalid handle.\r\n"},
	{7, "Memory trashed.\r\n"},
	{8, "Not enough memory.\r\n"},
	{9, "Invalid block.\r\n"},
	{10, "Bad environment.\r\n"},
	{11, "Bad format.\r\n"},
	{12, "Invalid access.\r\n"},
	{13, "Invalid data.\r\n"},
	{14, "Out of memory.\r\n"},
	{15, "Invalid drive.\r\n"},
	{16, "Can't delete current directory.\r\n"},
	{17, "Not same device.\r\n"},
	{18, "No more files.\r\n"},
	{19, "Write protected.\r\n"},
	{20, "Bad unit.\r\n"},
	{21, "Not ready.\r\n"},
	{22, "Bad command.\r\n"},
	{23, "CRC error.\r\n"},
	{24, "Bad length.\r\n"},
	{25, "Seek error.\r\n"},
	{26, "Not DOS disk.\r\n"},
	{27, "Sector not found.\r\n"},
	{28, "Out of paper.\r\n"},
	{29, "Write fault.\r\n"},
	{30, "Read fault.\r\n"},
	{31, "General failure.\r\n"},
	{32, "Sharing violation.\r\n"},
	{33, "Lock violation.\r\n"},
	{34, "Wrong disk.\r\n"},
	{36, "Sharing buffer exceeded.\r\n"},
	{38, "End of file.\r\n"},
	{39, "Disk full.\r\n"},
	{50, "Request not supported.\r\n"},
	{51, "Remote machine not listening.\r\n"},
	{52, "Duplicate network name.\r\n"},
	{53, "Bad network path.\r\n"},
	{54, "Network busy.\r\n"},
	{55, "Device does not exist.\r\n"},
	{56, "Too many commands.\r\n"},
	{57, "Adapter hardware error.\r\n"},
	{58, "Bad network response.\r\n"},
	{59, "Unexpected network error.\r\n"},
	{60, "Bad remote adapter.\r\n"},
	{61, "Print queue full.\r\n"},
	{62, "No spool space.\r\n"},
	{63, "Print canceled.\r\n"},
	{64, "Network name deleted.\r\n"},
	{65, "Network access denied.\r\n"},
	{66, "Bad device type.\r\n"},
	{67, "Bad network name.\r\n"},
	{68, "Too many network names.\r\n"},
	{69, "Too many network sessions.\r\n"},
	{70, "Sharing paused.\r\n"},
	{71, "Request not accepted.\r\n"},
	{72, "Redirector paused.\r\n"},
	{80, "File exists.\r\n"},
	{82, "Cannot create.\r\n"},
	{83, "Int24 failure.\r\n"},
	{84, "Out of structures.\r\n"},
	{85, "Already assigned.\r\n"},
	{86, "Invalid password.\r\n"},
	{87, "Invalid parameter.\r\n"},
	{88, "Net write fault.\r\n"},
	{89, "No process slots.\r\n"},
	{100, "Too many semaphores.\r\n"},
	{101, "Exclusive semaphore already owned.\r\n"},
	{102, "Semaphore is set.\r\n"},
	{103, "Too many semaphore requests.\r\n"},
	{104, "Invalid at interrupt time.\r\n"},
	{105, "Semaphore owner died.\r\n"},
	{106, "Semaphore user limit.\r\n"},
	{108, "Drive locked.\r\n"},
	{109, "Broken pipe.\r\n"},
	{110, "Open failed.\r\n"},
	{111, "Buffer overflow.\r\n"},
	{112, "Disk full.\r\n"},
	{113, "No more search handles.\r\n"},
	{114, "Invalid target handle.\r\n"},
	{117, "Invalid IOCTL.\r\n"},
	{118, "Invalid verify switch.\r\n"},
	{119, "Bad driver level.\r\n"},
	{120, "Call not implemented.\r\n"},
	{121, "Semaphore timeout.\r\n"},
	{122, "Insufficient buffer.\r\n"},
	{123, "Invalid name.\r\n"},
	{124, "Invalid level.\r\n"},
	{125, "No volume label.\r\n"},
	{126, "Module not found.\r\n"},
	{127, "Procedure not found.\r\n"},
	{128, "No children to wait for.\r\n"},
	{129, "Child process has not completed.\r\n"},
	{130, "Invalid use of direct access handle.\r\n"},
	{131, "Negative seek.\r\n"},
	{132, "Seek error.\r\n"},
	{133, "Drive is a JOIN target.\r\n"},
	{134, "Drive is already JOINed.\r\n"},
	{135, "Drive is already SUBSTed.\r\n"},
	{136, "Drive is not JOINed.\r\n"},
	{137, "Drive is not SUBSTed.\r\n"},
	{138, "Attempt to JOIN onto a JOINed drive.\r\n"},
	{139, "Attempt to SUBST onto a SUBSTed drive.\r\n"},
	{140, "Attempt to JOIN to a SUBSTed drive.\r\n"},
	{141, "Attempt to SUBST to a JOINed drive.\r\n"},
	{142, "Drive is busy.\r\n"},
	{143, "Same drive.\r\n"},
	{144, "Not top-level directory.\r\n"},
	{145, "Directory is not empty.\r\n"},
	{146, "Path is in use as a SUBST.\r\n"},
	{147, "Path is in use as a JOIN.\r\n"},
	{148, "Path is busy.\r\n"},
	{149, "Already a SUBST target.\r\n"},
	{150, "System trace not specified or disallowed.\r\n"},
	{151, "Event count for DosMuxSemWait incorrect.\r\n"},
	{152, "Too many waiters for DosMuxSemWait.\r\n"},
	{153, "DosSemMuxWait list invalid.\r\n"},
	{154, "Volume label too long.\r\n"},
	{155, "Too many TCBs.\r\n"},
	{156, "Signal refused.\r\n"},
	{157, "Segment discarded.\r\n"},
	{158, "Segment not locked.\r\n"},
	{159, "Bad thread ID address.\r\n"},
	{160, "Bad arguments to DosExecPgm.\r\n"},
	{161, "Path is invalid.\r\n"},
	{162, "Signal pending.\r\n"},
	{164, "Max system-wide thread count reached.\r\n"},
	{167, "Lock failed.\r\n"},
	{170, "Resource in use.\r\n"},
	{173, "Cancel violation.\r\n"},
	{174, "Atomic locks not supported.\r\n"},
	{180, "Invalid segment number.\r\n"},
	{183, "File already exists.\r\n"},
	{186, "Invalid flag number.\r\n"},
	{187, "Semaphore name not found.\r\n"},
	{196, "Dynlink from invalid ring.\r\n"},
	{197, "IOPL not enabled.\r\n"},
	{199, "Auto data segment exceeds 64k.\r\n"},
	{200, "Ring 2 segment must be movable.\r\n"},
	{203, "Environment variable not found.\r\n"},
	{205, "No signal sent.\r\n"},
	{206, "File name is too long.\r\n"},
	{207, "Ring 2 stack in use.\r\n"},
	{208, "Error in use of filename wildcards.\r\n"},
	{209, "Invalid signal number.\r\n"},
	{210, "Error setting signal handler.\r\n"},
	{212, "Segment locked.\r\n"},
	{214, "Too many modules.\r\n"},
	{215, "Nesting LoadModule calls not allowed.\r\n"},
	{216, "Machine type mismatch.\r\n"},
	{230, "Bad pipe.\r\n"},
	{231, "Pipe busy.\r\n"},
	{232, "Pipe closed.\r\n"},
	{233, "Pipe not connected.\r\n"},
	{234, "More data available.\r\n"},
	{240, "Session canceled.\r\n"},
	{254, "Invalid extended attribute name.\r\n"},
	{255, "Extended attribute list inconsistent.\r\n"},
	{259, "No more data available.\r\n"},
	{266, "Cannot use Copy API.\r\n"},
	{267, "Directory name invalid.\r\n"},
	{275, "Extended attributes didn't fit.\r\n"},
	{276, "Extended attribute file corrupt.\r\n"},
	{277, "Extended attribute table full.\r\n"},
	{278, "Invalid extended attribute handle.\r\n"},
	{282, "Extended attributes not supported.\r\n"},
	{288, "Mutex not owned by caller.\r\n"},
	{298, "Too many posts to semaphore.\r\n"},
	{299, "Read/WriteProcessMemory partially completed.\r\n"},
	{300, "The oplock wasn't granted.\r\n"},
	{301, "Invalid oplock message received.\r\n"},
	{302, "Disk is too fragmented.\r\n"},
	{303, "File cannot be opened because it is in the process of being deleted.\r\n"},
	{304, "Short name settings incompatible with global registry setting.\r\n"},
	{305, "Short names are not enabled on this volume.\r\n"},
	{306, "Security stream is inconsistent.\r\n"},
	{307, "File lock operation cannot be processed due to invalid byte range.\r\n"},
	{308, "Subsystem for supporting image type is not present.\r\n"},
	{309, "Notification GUID is already defined.\r\n"},
	{310, "Invalid exception handler.\r\n"},
	{311, "Duplicate privileges for the token.\r\n"},
	{312, "No ranges could be processed.\r\n"},
	{313, "Operation not allowed on system file.\r\n"},
	{314, "Disk resources have been exhausted.\r\n"},
	{315, "Invalid token.\r\n"},
	{316, "Command feature not supported on the device.\r\n"},
	{318, "Scope not found.\r\n"},
	{319, "The specified Central Access Policy is undefined.\r\n"},
	{320, "Central Access Policy from Active Directory is invalid.\r\n"},
	{321, "Device is unreachable.\r\n"},
	{322, "Target device has insufficient resources to complete the operation.\r\n"},
	{323, "A data integrity checksum error occurred. Data in the file stream is corrupt.\r\n"},
	{324, "Cannot modify both KERNEL and normal Extended Attributes in one operation.\r\n"},
	{326, "Device does not support file-level TRIM.\r\n"},
	{487, "Invalid address.\r\n"},
	{534, "Arithmetic overflow.\r\n"},
	{535, "Pipe connected.\r\n"},
	{536, "Pipe listening.\r\n"},
	{994, "Extended attribute access denied.\r\n"},
	{995, "I/O operation aborted.\r\n"},
	{996, "Overlapped I/O incomplete.\r\n"},
	{997, "Overlapped I/O pending.\r\n"},
	{998, "No access to memory location.\r\n"},
	{999, "Swap error.\r\n"},
	{1001, "Stack overflow.\r\n"},
	{1002, "Invalid message.\r\n"},
	{1003, "Cannot complete.\r\n"},
	{1004, "Invalid flags.\r\n"},
	{1005, "Unrecognized volume.\r\n"},
	{1006, "File invalid.\r\n"},
	{1007, "Cannot run full-screen.\r\n"},
	{1008, "Nonexistent token.\r\n"},
	{1009, "Registry corrupt.\r\n"},
	{1010, "Invalid key.\r\n"},
	{1011, "Can't open registry key.\r\n"},
	{1012, "Can't read registry key.\r\n"},
	{1013, "Can't write registry key.\r\n"},
	{1014, "Registry has been recovered.\r\n"},
	{1015, "Registry is corrupt.\r\n"},
	{1016, "I/O to registry failed.\r\n"},
	{1017, "Not registry file.\r\n"},
	{1018, "Key deleted.\r\n"},
	{1019, "No registry log space.\r\n"},
	{1020, "Registry key has subkeys.\r\n"},
	{1021, "Subkey must be volatile.\r\n"},
	{1022, "Notify change request in progress.\r\n"},
	{1051, "Dependent services are running.\r\n"},
	{1052, "Invalid service control.\r\n"},
	{1053, "Service request timeout.\r\n"},
	{1054, "Cannot create service thread.\r\n"},
	{1055, "Service database locked.\r\n"},
	{1056, "Service already running.\r\n"},
	{1057, "Invalid service account.\r\n"},
	{1058, "Service is disabled.\r\n"},
	{1059, "Circular dependency.\r\n"},
	{1060, "Service does not exist.\r\n"},
	{1061, "Service cannot accept control message.\r\n"},
	{1062, "Service not active.\r\n"},
	{1063, "Service controller connect failed.\r\n"},
	{1064, "Exception in service.\r\n"},
	{1065, "Database does not exist.\r\n"},
	{1066, "Service-specific error.\r\n"},
	{1067, "Process aborted.\r\n"},
	{1068, "Service dependency failed.\r\n"},
	{1069, "Service login failed.\r\n"},
	{1070, "Service start-hang.\r\n"},
	{1071, "Invalid service lock.\r\n"},
	{1072, "Service marked for delete.\r\n"},
	{1073, "Service exists.\r\n"},
	{1074, "System running last-known-good config.\r\n"},
	{1075, "Service dependency deleted.\r\n"},
	{1076, "Boot already accepted as last-good config.\r\n"},
	{1077, "Service not started since last boot.\r\n"},
	{1078, "Duplicate service name.\r\n"},
	{1079, "Different service account.\r\n"},
	{1080, "Driver failure cannot be detected.\r\n"},
	{1081, "Process abort cannot be detected.\r\n"},
	{1082, "No recovery program for service.\r\n"},
	{1083, "Service not implemented by exe.\r\n"},
	{1100, "End of media.\r\n"},
	{1101, "Filemark detected.\r\n"},
	{1102, "Beginning of media.\r\n"},
	{1103, "Setmark detected.\r\n"},
	{1104, "No data detected.\r\n"},
	{1105, "Partition failure.\r\n"},
	{1106, "Invalid block length.\r\n"},
	{1107, "Device not partitioned.\r\n"},
	{1108, "Unable to lock media.\r\n"},
	{1109, "Unable to unload media.\r\n"},
	{1110, "Media changed.\r\n"},
	{1111, "I/O bus reset.\r\n"},
	{1112, "No media in drive.\r\n"},
	{1113, "No Unicode translation.\r\n"},
	{1114, "DLL initialization failed.\r\n"},
	{1115, "Shutdown in progress.\r\n"},
	{1116, "No shutdown in progress.\r\n"},
	{1117, "I/O device error.\r\n"},
	{1118, "No serial devices found.\r\n"},
	{1119, "Shared IRQ busy.\r\n"},
	{1120, "Serial I/O completed.\r\n"},
	{1121, "Serial I/O counter timeout.\r\n"},
	{1122, "Floppy ID address mark not found.\r\n"},
	{1123, "Floppy reports wrong cylinder.\r\n"},
	{1124, "Unknown floppy error.\r\n"},
	{1125, "Floppy registers inconsistent.\r\n"},
	{1126, "Hard disk recalibrate failed.\r\n"},
	{1127, "Hard disk operation failed.\r\n"},
	{1128, "Hard disk reset failed.\r\n"},
	{1129, "End of tape media.\r\n"},
	{1130, "Not enough server memory.\r\n"},
	{1131, "Possible deadlock.\r\n"},
	{1132, "Incorrect alignment.\r\n"},
	{1140, "Set-power-state vetoed.\r\n"},
	{1141, "Set-power-state failed.\r\n"},
	{1142, "Too many links.\r\n"},
	{1150, "Newer Windows version needed.\r\n"},
	{1151, "Wrong operating system.\r\n"},
	{1152, "Single-instance application.\r\n"},
	{1153, "Real-mode application.\r\n"},
	{1154, "Invalid DLL.\r\n"},
	{1155, "No associated application.\r\n"},
	{1156, "DDE failure.\r\n"},
	{1157, "DLL not found.\r\n"},
	{1158, "Out of user handles.\r\n"},
	{1159, "Message can only be used in synchronous calls.\r\n"},
	{1160, "The source element is empty.\r\n"},
	{1161, "The destination element is full.\r\n"},
	{1162, "The element address is invalid.\r\n"},
	{1163, "The magazine is not present.\r\n"},
	{1164, "The device needs reinitialization.\r\n"},
	{1165, "The device requires cleaning.\r\n"},
	{1166, "The device door is open.\r\n"},
	{1167, "The device is not connected.\r\n"},
	{1168, "Element not found.\r\n"},
	{1169, "No match found.\r\n"},
	{1170, "Property set not found.\r\n"},
	{1171, "Point not found.\r\n"},
	{1172, "No running tracking service.\r\n"},
	{1173, "No such volume ID.\r\n"},
	{1175, "Unable to remove the file to be replaced.\r\n"},
	{1176, "Unable to move the replacement file into place.\r\n"},
	{1177, "Moving the replacement file failed.\r\n"},
	{1178, "The journal is being deleted.\r\n"},
	{1179, "The journal is not active.\r\n"},
	{1180, "Potential matching file found.\r\n"},
	{1181, "The journal entry was deleted.\r\n"},
	{1200, "Invalid device name.\r\n"},
	{1201, "Connection unavailable.\r\n"},
	{1202, "Device already remembered.\r\n"},
	{1203, "No network or bad path.\r\n"},
	{1204, "Invalid network provider name.\r\n"},
	{1205, "Cannot open network connection profile.\r\n"},
	{1206, "Corrupt network connection profile.\r\n"},
	{1207, "Not a container.\r\n"},
	{1208, "Extended error.\r\n"},
	{1209, "Invalid group name.\r\n"},
	{1210, "Invalid computer name.\r\n"},
	{1211, "Invalid event name.\r\n"},
	{1212, "Invalid domain name.\r\n"},
	{1213, "Invalid service name.\r\n"},
	{1214, "Invalid network name.\r\n"},
	{1215, "Invalid share name.\r\n"},
	{1216, "Invalid password.\r\n"},
	{1217, "Invalid message name.\r\n"},
	{1218, "Invalid message destination.\r\n"},
	{1219, "Session credential conflict.\r\n"},
	{1220, "Remote session limit exceeded.\r\n"},
	{1221, "Duplicate domain or workgroup name.\r\n"},
	{1222, "No network.\r\n"},
	{1223, "Operation canceled by user.\r\n"},
	{1224, "File has a user-mapped section.\r\n"},
	{1225, "Connection refused.\r\n"},
	{1226, "Connection gracefully closed.\r\n"},
	{1227, "Address already associated with transport endpoint.\r\n"},
	{1228, "Address not associated with transport endpoint.\r\n"},
	{1229, "Connection invalid.\r\n"},
	{1230, "Connection is active.\r\n"},
	{1231, "Network unreachable.\r\n"},
	{1232, "Host unreachable.\r\n"},
	{1233, "Protocol unreachable.\r\n"},
	{1234, "Port unreachable.\r\n"},
	{1235, "Request aborted.\r\n"},
	{1236, "Connection aborted.\r\n"},
	{1237, "Please retry operation.\r\n"},
	{1238, "Connection count limit reached.\r\n"},
	{1239, "Login time restriction.\r\n"},
	{1240, "Login workstation restriction.\r\n"},
	{1241, "Incorrect network address.\r\n"},
	{1242, "Service already registered.\r\n"},
	{1243, "Service not found.\r\n"},
	{1244, "User not authenticated.\r\n"},
	{1245, "User not logged on.\r\n"},
	{1246, "Continue work in progress.\r\n"},
	{1247, "Already initialized.\r\n"},
	{1248, "No more local devices.\r\n"},
	{1249, "The site does not exist.\r\n"},
	{1250, "The domain controller already exists.\r\n"},
	{1251, "Supported only when connected.\r\n"},
	{1252, "Perform operation even when nothing changed.\r\n"},
	{1253, "The user profile is invalid.\r\n"},
	{1254, "Not supported on Small Business Server.\r\n"},
	{1300, "Not all privileges assigned.\r\n"},
	{1301, "Some security IDs not mapped.\r\n"},
	{1302, "No quotas for account.\r\n"},
	{1303, "Local user session key.\r\n"},
	{1304, "Password too complex for LM.\r\n"},
	{1305, "Unknown revision.\r\n"},
	{1306, "Incompatible revision levels.\r\n"},
	{1307, "Invalid owner.\r\n"},
	{1308, "Invalid primary group.\r\n"},
	{1309, "No impersonation token.\r\n"},
	{1310, "Can't disable mandatory group.\r\n"},
	{1311, "No logon servers available.\r\n"},
	{1312, "No such logon session.\r\n"},
	{1313, "No such privilege.\r\n"},
	{1314, "Privilege not held.\r\n"},
	{1315, "Invalid account name.\r\n"},
	{1316, "User already exists.\r\n"},
	{1317, "No such user.\r\n"},
	{1318, "Group already exists.\r\n"},
	{1319, "No such group.\r\n"},
	{1320, "User already in group.\r\n"},
	{1321, "User not in group.\r\n"},
	{1322, "Can't delete last admin user.\r\n"},
	{1323, "Wrong password.\r\n"},
	{1324, "Ill-formed password.\r\n"},
	{1325, "Password restriction.\r\n"},
	{1326, "Logon failure.\r\n"},
	{1327, "Account restriction.\r\n"},
	{1328, "Invalid logon hours.\r\n"},
	{1329, "Invalid workstation.\r\n"},
	{1330, "Password expired.\r\n"},
	{1331, "Account disabled.\r\n"},
	{1332, "No security ID mapped.\r\n"},
	{1333, "Too many LUIDs requested.\r\n"},
	{1334, "LUIDs exhausted.\r\n"},
	{1335, "Invalid sub authority.\r\n"},
	{1336, "Invalid ACL.\r\n"},
	{1337, "Invalid SID.\r\n"},
	{1338, "Invalid security descriptor.\r\n"},
	{1340, "Bad inherited ACL.\r\n"},
	{1341, "Server disabled.\r\n"},
	{1342, "Server not disabled.\r\n"},
	{1343, "Invalid ID authority.\r\n"},
	{1344, "Allotted space exceeded.\r\n"},
	{1345, "Invalid group attributes.\r\n"},
	{1346, "Bad impersonation level.\r\n"},
	{1347, "Can't open anonymous security token.\r\n"},
	{1348, "Bad validation class.\r\n"},
	{1349, "Bad token type.\r\n"},
	{1350, "No security on object.\r\n"},
	{1351, "Can't access domain information.\r\n"},
	{1352, "Invalid server state.\r\n"},
	{1353, "Invalid domain state.\r\n"},
	{1354, "Invalid domain role.\r\n"},
	{1355, "No such domain.\r\n"},
	{1356, "Domain already exists.\r\n"},
	{1357, "Domain limit exceeded.\r\n"},
	{1358, "Internal database corruption.\r\n"},
	{1359, "Internal error.\r\n"},
	{1360, "Generic access types not mapped.\r\n"},
	{1361, "Bad descriptor format.\r\n"},
	{1362, "Not a logon process.\r\n"},
	{1363, "Logon session ID exists.\r\n"},
	{1364, "Unknown authentication package.\r\n"},
	{1365, "Bad logon session state.\r\n"},
	{1366, "Logon session ID collision.\r\n"},
	{1367, "Invalid logon type.\r\n"},
	{1368, "Cannot impersonate.\r\n"},
	{1369, "Invalid transaction state.\r\n"},
	{1370, "Security DB commit failure.\r\n"},
	{1371, "Account is built-in.\r\n"},
	{1372, "Group is built-in.\r\n"},
	{1373, "User is built-in.\r\n"},
	{1374, "Group is primary for user.\r\n"},
	{1375, "Token already in use.\r\n"},
	{1376, "No such local group.\r\n"},
	{1377, "User not in local group.\r\n"},
	{1378, "User already in local group.\r\n"},
	{1379, "Local group already exists.\r\n"},
	{1380, "Logon type not granted.\r\n"},
	{1381, "Too many secrets.\r\n"},
	{1382, "Secret too long.\r\n"},
	{1383, "Internal security DB error.\r\n"},
	{1384, "Too many context IDs.\r\n"},
	{1385, "Logon type not granted.\r\n"},
	{1386, "Cross-encrypted NT password required.\r\n"},
	{1387, "No such member.\r\n"},
	{1388, "Invalid member.\r\n"},
	{1389, "Too many SIDs.\r\n"},
	{1390, "Cross-encrypted LM password required.\r\n"},
	{1391, "No inheritable components.\r\n"},
	{1392, "File or directory corrupt.\r\n"},
	{1393, "Disk is corrupt.\r\n"},
	{1394, "No user session key.\r\n"},
	{1395, "License quota exceeded.\r\n"},
	{1396, "Wrong target name.\r\n"},
	{1397, "Mutual authentication failed.\r\n"},
	{1398, "Time skew between client and server.\r\n"},
	{1400, "Invalid window handle.\r\n"},
	{1401, "Invalid menu handle.\r\n"},
	{1402, "Invalid cursor handle.\r\n"},
	{1403, "Invalid accelerator table handle.\r\n"},
	{1404, "Invalid hook handle.\r\n"},
	{1405, "Invalid DWP handle.\r\n"},
	{1406, "Can't create top-level child window.\r\n"},
	{1407, "Can't find window class.\r\n"},
	{1408, "Window owned by another thread.\r\n"},
	{1409, "Hotkey already registered.\r\n"},
	{1410, "Class already exists.\r\n"},
	{1411, "Class does not exist.\r\n"},
	{1412, "Class has open windows.\r\n"},
	{1413, "Invalid index.\r\n"},
	{1414, "Invalid icon handle.\r\n"},
	{1415, "Private dialog index.\r\n"},
	{1416, "List box ID not found.\r\n"},
	{1417, "No wildcard characters.\r\n"},
	{1418, "Clipboard not open.\r\n"},
	{1419, "Hotkey not registered.\r\n"},
	{1420, "Not a dialog window.\r\n"},
	{1421, "Control ID not found.\r\n"},
	{1422, "Invalid combo box message.\r\n"},
	{1423, "Not a combo box window.\r\n"},
	{1424, "Invalid edit height.\r\n"},
	{1425, "DC not found.\r\n"},
	{1426, "Invalid hook filter.\r\n"},
	{1427, "Invalid filter procedure.\r\n"},
	{1428, "Hook procedure needs module handle.\r\n"},
	{1429, "Global-only hook procedure.\r\n"},
	{1430, "Journal hook already set.\r\n"},
	{1431, "Hook procedure not installed.\r\n"},
	{1432, "Invalid list box message.\r\n"},
	{1433, "Invalid LB_SETCOUNT sent.\r\n"},
	{1434, "No tab stops on this list box.\r\n"},
	{1435, "Can't destroy object owned by another thread.\r\n"},
	{1436, "Child window menus not allowed.\r\n"},
	{1437, "Window has no system menu.\r\n"},
	{1438, "Invalid message box style.\r\n"},
	{1439, "Invalid SPI parameter.\r\n"},
	{1440, "Screen already locked.\r\n"},
	{1441, "Window handles have different parents.\r\n"},
	{1442, "Not a child window.\r\n"},
	{1443, "Invalid GW command.\r\n"},
	{1444, "Invalid thread ID.\r\n"},
	{1445, "Not an MDI child window.\r\n"},
	{1446, "Popup menu already active.\r\n"},
	{1447, "No scrollbars.\r\n"},
	{1448, "Invalid scrollbar range.\r\n"},
	{1449, "Invalid ShowWin command.\r\n"},
	{1450, "No system resources.\r\n"},
	{1451, "No non-paged system resources.\r\n"},
	{1452, "No paged system resources.\r\n"},
	{1453, "No working set quota.\r\n"},
	{1454, "No page file quota.\r\n"},
	{1455, "Exceeded commitment limit.\r\n"},
	{1456, "Menu item not found.\r\n"},
	{1457, "Invalid keyboard handle.\r\n"},
	{1458, "Hook type not allowed.\r\n"},
	{1459, "Interactive window station required.\r\n"},
	{1460, "Timeout.\r\n"},
	{1461, "Invalid monitor handle.\r\n"},
	{1500, "Event log file corrupt.\r\n"},
	{1501, "Event log can't start.\r\n"},
	{1502, "Event log file full.\r\n"},
	{1503, "Event log file changed.\r\n"},
	{1601, "Installer service failed.\r\n"},
	{1602, "Installation aborted by user.\r\n"},
	{1603, "Installation failure.\r\n"},
	{1604, "Installation suspended.\r\n"},
	{1605, "Unknown product.\r\n"},
	{1606, "Unknown feature.\r\n"},
	{1607, "Unknown component.\r\n"},
	{1608, "Unknown property.\r\n"},
	{1609, "Invalid handle state.\r\n"},
	{1610, "Bad configuration.\r\n"},
	{1611, "Index is missing.\r\n"},
	{1612, "Installation source is missing.\r\n"},
	{1613, "Wrong installation package version.\r\n"},
	{1614, "Product uninstalled.\r\n"},
	{1615, "Invalid query syntax.\r\n"},
	{1616, "Invalid field.\r\n"},
	{1617, "Device removed.\r\n"},
	{1618, "Installation already running.\r\n"},
	{1619, "Installation package failed to open.\r\n"},
	{1620, "Installation package is invalid.\r\n"},
	{1621, "Installer user interface failed.\r\n"},
	{1622, "Failed to open installation log file.\r\n"},
	{1623, "Installation language not supported.\r\n"},
	{1624, "Installation transform failed to apply.\r\n"},
	{1625, "Installation package rejected.\r\n"},
	{1626, "Function could not be called.\r\n"},
	{1627, "Function failed.\r\n"},
	{1628, "Invalid table.\r\n"},
	{1629, "Data type mismatch.\r\n"},
	{1630, "Unsupported type.\r\n"},
	{1631, "Creation failed.\r\n"},
	{1632, "Temporary directory not writable.\r\n"},
	{1633, "Installation platform not supported.\r\n"},
	{1634, "Installer not used.\r\n"},
	{1635, "Failed to open the patch package.\r\n"},
	{1636, "Invalid patch package.\r\n"},
	{1637, "Unsupported patch package.\r\n"},
	{1638, "Another version is installed.\r\n"},
	{1639, "Invalid command line.\r\n"},
	{1640, "Remote installation not allowed.\r\n"},
	{1641, "Reboot initiated after successful install.\r\n"},
	{1700, "Invalid string binding.\r\n"},
	{1701, "Wrong kind of binding.\r\n"},
	{1702, "Invalid binding.\r\n"},
	{1703, "RPC protocol sequence not supported.\r\n"},
	{1704, "Invalid RPC protocol sequence.\r\n"},
	{1705, "Invalid string UUID.\r\n"},
	{1706, "Invalid endpoint format.\r\n"},
	{1707, "Invalid network address.\r\n"},
	{1708, "No endpoint found.\r\n"},
	{1709, "Invalid timeout value.\r\n"},
	{1710, "Object UUID not found.\r\n"},
	{1711, "UUID already registered.\r\n"},
	{1712, "UUID type already registered.\r\n"},
	{1713, "Server already listening.\r\n"},
	{1714, "No protocol sequences registered.\r\n"},
	{1715, "RPC server not listening.\r\n"},
	{1716, "Unknown manager type.\r\n"},
	{1717, "Unknown interface.\r\n"},
	{1718, "No bindings.\r\n"},
	{1719, "No protocol sequences.\r\n"},
	{1720, "Can't create endpoint.\r\n"},
	{1721, "Out of resources.\r\n"},
	{1722, "RPC server unavailable.\r\n"},
	{1723, "RPC server too busy.\r\n"},
	{1724, "Invalid network options.\r\n"},
	{1725, "No RPC call active.\r\n"},
	{1726, "RPC call failed.\r\n"},
	{1727, "RPC call failed and didn't execute.\r\n"},
	{1728, "RPC protocol error.\r\n"},
	{1730, "Unsupported transfer syntax.\r\n"},
	{1732, "Unsupported type.\r\n"},
	{1733, "Invalid tag.\r\n"},
	{1734, "Invalid array bounds.\r\n"},
	{1735, "No entry name.\r\n"},
	{1736, "Invalid name syntax.\r\n"},
	{1737, "Unsupported name syntax.\r\n"},
	{1739, "No network address.\r\n"},
	{1740, "Duplicate endpoint.\r\n"},
	{1741, "Unknown authentication type.\r\n"},
	{1742, "Maximum calls too low.\r\n"},
	{1743, "String too long.\r\n"},
	{1744, "Protocol sequence not found.\r\n"},
	{1745, "Procedure number out of range.\r\n"},
	{1746, "Binding has no authentication data.\r\n"},
	{1747, "Unknown authentication service.\r\n"},
	{1748, "Unknown authentication level.\r\n"},
	{1749, "Invalid authentication identity.\r\n"},
	{1750, "Unknown authorization service.\r\n"},
	{1751, "Invalid entry.\r\n"},
	{1752, "Can't perform operation.\r\n"},
	{1753, "Endpoints not registered.\r\n"},
	{1754, "Nothing to export.\r\n"},
	{1755, "Incomplete name.\r\n"},
	{1756, "Invalid version option.\r\n"},
	{1757, "No more members.\r\n"},
	{1758, "Not all objects unexported.\r\n"},
	{1759, "Interface not found.\r\n"},
	{1760, "Entry already exists.\r\n"},
	{1761, "Entry not found.\r\n"},
	{1762, "Name service unavailable.\r\n"},
	{1763, "Invalid network address family.\r\n"},
	{1764, "Operation not supported.\r\n"},
	{1765, "No security context available.\r\n"},
	{1766, "RPCInternal error.\r\n"},
	{1767, "RPC divide-by-zero.\r\n"},
	{1768, "Address error.\r\n"},
	{1769, "Floating-point divide-by-zero.\r\n"},
	{1770, "Floating-point underflow.\r\n"},
	{1771, "Floating-point overflow.\r\n"},
	{1772, "No more entries.\r\n"},
	{1773, "Character translation table open failed.\r\n"},
	{1774, "Character translation table file too small.\r\n"},
	{1775, "Null context handle.\r\n"},
	{1777, "Context handle damaged.\r\n"},
	{1778, "Binding handle mismatch.\r\n"},
	{1779, "Cannot get call handle.\r\n"},
	{1780, "Null reference pointer.\r\n"},
	{1781, "Enumeration value out of range.\r\n"},
	{1782, "Byte count too small.\r\n"},
	{1783, "Bad stub data.\r\n"},
	{1784, "Invalid user buffer.\r\n"},
	{1785, "Unrecognized media.\r\n"},
	{1786, "No trust secret.\r\n"},
	{1787, "No trust SAM account.\r\n"},
	{1788, "Trusted domain failure.\r\n"},
	{1789, "Trusted relationship failure.\r\n"},
	{1790, "Trust logon failure.\r\n"},
	{1791, "RPC call already in progress.\r\n"},
	{1792, "NETLOGON is not started.\r\n"},
	{1793, "Account expired.\r\n"},
	{1794, "Redirector has open handles.\r\n"},
	{1795, "Printer driver already installed.\r\n"},
	{1796, "Unknown port.\r\n"},
	{1797, "Unknown printer driver.\r\n"},
	{1798, "Unknown print processor.\r\n"},
	{1799, "Invalid separator file.\r\n"},
	{1800, "Invalid priority.\r\n"},
	{1801, "Invalid printer name.\r\n"},
	{1802, "Printer already exists.\r\n"},
	{1803, "Invalid printer command.\r\n"},
	{1804, "Invalid data type.\r\n"},
	{1805, "Invalid environment.\r\n"},
	{1806, "No more bindings.\r\n"},
	{1807, "Can't log on with inter-domain trust account.\r\n"},
	{1808, "Can't log on with workstation trust account.\r\n"},
	{1809, "Can't log on with server trust account.\r\n"},
	{1810, "Domain trust information inconsistent.\r\n"},
	{1811, "Server has open handles.\r\n"},
	{1812, "Resource data not found.\r\n"},
	{1813, "Resource type not found.\r\n"},
	{1814, "Resource name not found.\r\n"},
	{1815, "Resource language not found.\r\n"},
	{1816, "Not enough quota.\r\n"},
	{1817, "No interfaces.\r\n"},
	{1818, "RPC call canceled.\r\n"},
	{1819, "Binding incomplete.\r\n"},
	{1820, "RPC comm failure.\r\n"},
	{1821, "Unsupported authorization level.\r\n"},
	{1822, "No principal name registered.\r\n"},
	{1823, "Not an RPC error.\r\n"},
	{1824, "UUID is local only.\r\n"},
	{1825, "Security package error.\r\n"},
	{1826, "Thread not canceled.\r\n"},
	{1827, "Invalid handle operation.\r\n"},
	{1828, "Wrong serializing package version.\r\n"},
	{1829, "Wrong stub version.\r\n"},
	{1830, "Invalid pipe object.\r\n"},
	{1831, "Wrong pipe order.\r\n"},
	{1832, "Wrong pipe version.\r\n"},
	{1898, "Group member not found.\r\n"},
	{1899, "Can't create endpoint mapper DB.\r\n"},
	{1900, "Invalid object.\r\n"},
	{1901, "Invalid time.\r\n"},
	{1902, "Invalid form name.\r\n"},
	{1903, "Invalid form size.\r\n"},
	{1904, "Already awaiting printer handle.\r\n"},
	{1905, "Printer deleted.\r\n"},
	{1906, "Invalid printer state.\r\n"},
	{1907, "User must change password.\r\n"},
	{1908, "Domain controller not found.\r\n"},
	{1909, "Account locked out.\r\n"},
	{1910, "Invalid pixel format.\r\n"},
	{1911, "Invalid driver.\r\n"},
	{1912, "Invalid object resolver set.\r\n"},
	{1913, "Incomplete RPC send.\r\n"},
	{1914, "Invalid asynchronous RPC handle.\r\n"},
	{1915, "Invalid asynchronous RPC call.\r\n"},
	{1916, "RPC pipe closed.\r\n"},
	{1917, "Discipline error on RPC pipe.\r\n"},
	{1918, "No data on RPC pipe.\r\n"},
	{1919, "No site name available.\r\n"},
	{1920, "The file cannot be accessed.\r\n"},
	{1921, "The filename cannot be resolved.\r\n"},
	{1922, "RPC entry type mismatch.\r\n"},
	{1923, "Not all objects could be exported.\r\n"},
	{1924, "The interface could not be exported.\r\n"},
	{1925, "The profile could not be added.\r\n"},
	{1926, "The profile element could not be added.\r\n"},
	{1927, "The profile element could not be removed.\r\n"},
	{1928, "The group element could not be added.\r\n"},
	{1929, "The group element could not be removed.\r\n"},
	{2221, "The username could not be found.\r\n"},
	{2250, "This network connection does not exist.\r\n"},
	{4390, "File or directory is not a reparse point.\r\n"},
	{10004, "Call interrupted.\r\n"},
	{10009, "Invalid file handle.\r\n"},
	{10013, "Access denied.\r\n"},
	{10014, "Invalid pointer address.\r\n"},
	{10022, "Invalid argument.\r\n"},
	{10024, "Too many open files.\r\n"},
	{10049, "Cannot assign requested address.\r\n"},
	{10054, "Connection reset by peer.\r\n"},
	{10061, "Connection refused.\r\n"},
	{11001, "Host not found.\r\n"},
	{11002, "Nonauthoritative host not found.\r\n"},
	{11003, "Nonrecoverable error.\r\n"},
	{11004, "Name valid, no data record.\r\n"},
	{0x80004001, "Not implemented.\r\n"},
	{0x80004005, "Call failed.\r\n"},
	{0x80092009, "Unable to find matching object.\r\n"},
	{0x800B0100, "No Signature found in file.\r\n"},
	{0x887A0001, "Invalid call.\r\n"},
	{0x887A0022, "Resource is not currently available.\r\n"},
};

static_assert(std::is_sorted(std::begin(kErrorMessages), std::end(kErrorMessages),
							 [](const ErrorMessage &a, const ErrorMessage &b) { return a.code < b.code; }),
			  "System error messages must be sorted by code");

} // namespace

namespace kernel32 {

const char *lookupSystemMessage(DWORD code) {
	const auto it = std::lower_bound(std::begin(kErrorMessages), std::end(kErrorMessages), code,
									 [](const ErrorMessage &message, DWORD value) { return message.code < value; });
	return it != std::end(kErrorMessages) && it->code == code ? it->text : nullptr;
}

} // namespace kernel32
